spring.application.name=demo
spring.thymeleaf.cache=false
spring.web.resources.cache.period=0
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:file:./data/testdb
spring.datasource.username=name
spring.datasource.password=password
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.mode=always


#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.url=jdbc:postgresql://192.168.1.100:5432/production_db
#spring.datasource.username=app_user
#spring.datasource.password=mypassword